### ISSUE TITLE
On Getting Rows Doesn't differentiate bet am and pm

### ISSUE THREAD

**Issue by ahmadessamshahin** [qax-os/excelize#1060] opened 2021-11-14 10:40 UTC
**Description**

date column with formate 12hr (am/pm)  doesn't differentiate bet if it is am or pm for example

5:30 am | 5:30 pm always read as 5:30 p12

**Comment by xuri** [comment] 2021-11-16 09:34
Thanks for your feedback, could you show us a complete, standalone example program or reproducible demo? Which version of the Excelize are you using, please gave a try the master branch code. And provide your input file attachment without confidential info if you can.

**Comment by manjdk** [comment] 2021-11-18 13:43
Hello,
I am facing same issue. First screenshot is showing column format that is used, second - how column looks like in excel xlsx sheet, and last one - what result is. No matter AM or PM is used - that strange `p12` value appears and time is not correct. Version I am using is v2.4.1.

![Screenshot from 2021-11-18 15-34-17](https://user-images.githubusercontent.com/46564367/142426322-36bce9f4-8279-4844-9029-24498e14bb79.png)
![Screenshot from 2021-11-18 15-36-48](https://user-images.githubusercontent.com/46564367/142426344-08c9654e-12b2-460b-add2-b5e2d9fca486.png)
![Screenshot from 2021-11-18 15-37-10](https://user-images.githubusercontent.com/46564367/142426351-8f950446-3f3f-4240-8abd-14559adbb609.png)

**Comment by xuri** [comment] 2021-11-20 03:32
Thanks for your issue, I have fixed it, please upgrade to the master branch code, and this patch will be released in the next version.

**Closed** 2021-11-20 03:31 UTC
Labels: confirmed, in progress
