### ISSUE TITLE
Empty cell in tabular data results in wrong slice length

### ISSUE THREAD

**Issue by duysqubix** [qax-os/excelize#1135] opened 2022-02-01 01:55 UTC
**Description**
When reading tabular data if a cell value is missing under the last header, the string slice is one less the rest.

**Steps to reproduce the issue:**
1. Create a simple xlsx file with the following

| col1 | col2 | col3 | col4 |   
|------|------|------|------|
| a    | b    | c    | d    |   
|      | b    | c    | d    |   
| a    |      | c    | d    |   
| a    | b    |     | d     |
|a     | b    |  c |      |   

2. Open file and read rows
```go
package main

import (
    "fmt"

    "github.com/xuri/excelize/v2"
)

func main() {
    f, err := excelize.OpenFile("Book1.xlsx")
    if err != nil {
        fmt.Println(err)
        return
    }
    defer func() {
        // Close the spreadsheet.
        if err := f.Close(); err != nil {
            fmt.Println(err)
        }
    }()

    // Get all the rows in the Sheet1.
    rows, err := f.GetRows("Sheet1")
    if err != nil {
        fmt.Println(err)
        return
    }
    for _, row := range rows {
        fmt.Printf("%v, %v\n", row, len(row))
    }
}

```

**Describe the results you received:**

If you run the above code you will get the following output which lead to validation errors

```
[col1 col2 col3 col4], 4
[a b c d], 4
[ b c d], 4
[a  c d], 4
[a b  d], 4
[a b c], 3 // VALIDATION errors
```

**Describe the results you expected:**

I expect the slices to be the same length

**Output of `go version`:**

```text
1.17.5 linux/amd64
```

**Excelize version or commit ID:**

```text
v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**
Linux Ubuntu WSL2.0

** My workaround -- not the best but maybe can help you

```go
var headerLen int

firstRow := true
for _, row := range rows{
  if firstRow{
    headerLen = len(row)
    firstRow = false
  }

  // validate here
  for {
    if len(row) != headerLen{
      row = append(row, "")
      continue
    }
   break
  }
}

```

**Comment by xuri** [comment] 2022-02-01 03:43
Thanks for your issue, as the documentation of the [`GetRows`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.GetRows) function says, the tail continuously empty cell in each row will be skipped.

**Comment by xuri** [comment] 2022-09-09 05:29
Hi @duysqubix, I have made made a figure in issue #1245 to explain what kind of cells will be skipped for your reference, and I closed this issue. If you have any questions, please let me know to reopen this anytime.

**Closed by xuri** 2022-09-09 05:29 UTC

**Comment by night1008** [comment] 2024-08-13 07:22
Why still exist the issue in v2.8.0

**Comment by xuri** [comment] 2024-08-13 07:27
This is not an issue, that by design. I intentionally made the `GetRows` function return cells on each as is, would not fill empty cell on the tail of each row. I already explained what kind of cells will be skipped in issue #1245.

**Comment by night1008** [comment] 2024-08-13 08:26
ok, thanks.
