### ISSUE TITLE
traversing the rows and cols by axis merged cells seem to return the same data

### ISSUE THREAD

**Issue by rbucker** [qax-os/excelize#983] opened 2021-08-06 21:14 UTC
The purpose of my app is to convert an XLSX file to a CSV or TSV. As I looped through the rows and columns I was able to GetCellValue() ... but if a set of cells were merged then any axis that overlapped that cell returned the same data resulting in many duplicated cells in the output. ALSO because the spreadsheet is a form... there is some parsing going on to determine where the data is.

Is there a sensible way to create a TSV?

**Comment by xuri** [comment] 2021-08-07 14:50
All cells value will be same in a merged range, this is by design. You can get merged range by [`GetMergeCells`](https://xuri.me/excelize/en/cell.html#GetMergeCells), and skip duplicate value in the same range as your need.

**Comment by rbucker** [comment] 2021-08-07 18:53
The GetMergeCells() returns an array of merged cell definitions.... So while I am trying to convert from xlsx to tsv... scanning all rows and columns... I have to pull the list of merged cells and determine if [a] it's the first cell in the merge [b] it's not the first cell in the merge.... and since I need to convert my cell's axis position to something that can be compared to the mergecell start/end axis position... some efficient helper functions would be great.

If that's not ok then closing the ticket is ok. Tanks

**Comment by xuri** [comment] 2021-08-08 10:43
There are some coordinates parse functions in the `lib.go`, I wish it will be helpful for you.

**Closed by xuri** 2021-08-08 10:43 UTC
