### ISSUE TITLE
error download file api to vue browser

### ISSUE THREAD

**Issue by danzf** [qax-os/excelize#2047] opened 2024-12-18 05:17 UTC
func (h *BookingMuseumHandler) DownloadExcels(c echo.Context) error {

    data, _, err := h.bookingUcase.Fetch(ctx, au, &params)
    if err != nil {
        return err
    }

    // Prepare the response data
    pubRes := []domain.ListBookingMuseumDataResponse{}
    for _, row := range data {
        res := domain.ListBookingMuseumDataResponse{
            ID:                row.ID,
            Nama:              row.PengunjungBookings.Nama,
            Email:             row.PengunjungBookings.Email,
            Kategori:          row.KategoriBookings.Nama,
            Sesi:              row.SesiBookings.Nama,
            JumlahPengunjung:  row.JumlahPengunjung,
            TanggalBerkunjung: row.TanggalBerkunjung,
            Dokumen:           row.DocBookings.Doc,
            BuktiBayarBookings: row.BuktiBayarBookings.Bukti,
            Status:            row.Status,
        }

        pubRes = append(pubRes, res)
    }

	
    // Create a new Excel file
    f := excelize.NewFile()
    index, err := f.NewSheet("Booking Museum")
    if err != nil {
        return err
    }
    f.SetActiveSheet(index)
	// Simpan file sementara di server untuk debugging

    // Set header
    headers := []string{
        "ID", "Nama", "Email", "Kategori", "Sesi", "Jumlah Pengunjung", "Tanggal Berkunjung", "Dokumen", "Bukti Bayar", "Status",
    }
    for col, header := range headers {
        f.SetCellValue("Booking Museum", fmt.Sprintf("%s1", string('A'+col)), header)
    }

    // Write data to Excel file
    for i, res := range pubRes {
        f.SetCellValue("Booking Museum", fmt.Sprintf("A%d", i+2), strconv.FormatInt(res.ID, 10))
        f.SetCellValue("Booking Museum", fmt.Sprintf("B%d", i+2), res.Nama)
        f.SetCellValue("Booking Museum", fmt.Sprintf("C%d", i+2), res.Email)
        f.SetCellValue("Booking Museum", fmt.Sprintf("D%d", i+2), res.Kategori)
        f.SetCellValue("Booking Museum", fmt.Sprintf("E%d", i+2), res.Sesi)
        f.SetCellValue("Booking Museum", fmt.Sprintf("F%d", i+2), strconv.FormatInt(res.JumlahPengunjung, 10))
        f.SetCellValue("Booking Museum", fmt.Sprintf("G%d", i+2), res.TanggalBerkunjung)
        f.SetCellValue("Booking Museum", fmt.Sprintf("H%d", i+2), res.Dokumen)
        f.SetCellValue("Booking Museum", fmt.Sprintf("I%d", i+2), res.BuktiBayarBookings)
        f.SetCellValue("Booking Museum", fmt.Sprintf("J%d", i+2), res.Status)
    }
	if err := f.SaveAs("temp_booking_museum.xlsx"); err != nil {
		return err
	}
	buf := new(bytes.Buffer)
	if err := f.Write(buf); err != nil {
		return c.JSON(500, "Failed to write Excel data to memory")
	}
	
	// Debugging: Periksa ukuran buffer
	fmt.Println("Buffer size:", buf.Len())  // Pastikan ukuran file lebih besar dari 0
	fmt.Printf("File size before sending: %d bytes\n", len(buf.Bytes()))

	// Pastikan kita mengirimkan data dalam bentuk binary (Blob)
	c.Response().Header().Set("Content-Disposition", "attachment; filename=booking_data.xlsx")
	c.Response().Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	c.Response().Header().Set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
	c.Response().Header().Set("Pragma", "no-cache")
	c.Response().Header().Set("Transfer-Encoding", "chunked")

	// Kirimkan data dalam bentuk byte array (Blob)
	return c.Blob(200, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buf.Bytes())
	}
	
         echo/v4 v4.11.3
	excelize/v2 v2.9.0 
	hasil dari pemanggilan api 
	
<img width="679" alt="Jepretan Layar 2024-12-18 pukul 12 17 07" src="https://github.com/user-attachments/assets/11f8290d-0aa5-4c9c-b401-8ae717ed172d" />

**Comment by xuri** [comment] 2024-12-19 05:58
Thanks for your issue. Could you show us a complete, standalone example program or reproducible demo with main function?

**Comment by xuri** [comment] 2024-12-23 05:24
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Closed by xuri** 2024-12-23 05:24 UTC
Labels: needs more info

**Comment by danzf** [comment] 2024-12-23 07:49
package main

import (
	"fmt"
	"github.com/gin-gonic/gin"
	"github.com/xuri/excelize/v2"
	"net/http"
	"os"
)

func ExportExcel(c *gin.Context) {
	// Data yang akan diekspor ke Excel
	data := []struct {
		ID     int    `json:"id"`
		Name   string `json:"name"`
		Age    int    `json:"age"`
		Email  string `json:"email"`
	}{
		{ID: 1, Name: "John Doe", Age: 29, Email: "john.doe@example.com"},
		{ID: 2, Name: "Jane Smith", Age: 34, Email: "jane.smith@example.com"},
		{ID: 3, Name: "Bob Johnson", Age: 45, Email: "bob.johnson@example.com"},
	}

	// Membuat file Excel baru
	f := excelize.NewFile()

	// Menulis header
	f.SetCellValue("Sheet1", "A1", "ID")
	f.SetCellValue("Sheet1", "B1", "Name")
	f.SetCellValue("Sheet1", "C1", "Age")
	f.SetCellValue("Sheet1", "D1", "Email")

	// Menulis data ke Excel
	for i, d := range data {
		row := i + 2 // Dimulai dari baris ke-2
		f.SetCellValue("Sheet1", fmt.Sprintf("A%d", row), d.ID)
		f.SetCellValue("Sheet1", fmt.Sprintf("B%d", row), d.Name)
		f.SetCellValue("Sheet1", fmt.Sprintf("C%d", row), d.Age)
		f.SetCellValue("Sheet1", fmt.Sprintf("D%d", row), d.Email)
	}

	// Menyimpan file Excel
	filePath := "./data.xlsx"
	if err := f.SaveAs(filePath); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{
			"error": fmt.Sprintf("failed to save file: %v", err),
		})
		return
	}

	// Mengirim file sebagai response
	c.Header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", "data.xlsx"))
	c.File(filePath)

	// Menghapus file setelah dikirim (untuk menghindari tumpukan file sementara)
	defer os.Remove(filePath)
}

func main() {
	// Membuat router Gin
	r := gin.Default()

	// Menyusun route untuk export Excel
	r.GET("/export-excel", ExportExcel)

	// Menjalankan server
	r.Run(":8080")
}

front en vue method
forceFileDownload(response) {
      const url = window.URL.createObjectURL(new Blob([response.data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'title.xls');
      document.body.appendChild(link);
      link.click();
    },
    async downloadExcel() {
    
     const response = await axios.get('http://localhost:8080/export-excel', {
          responseType: 'blob/arraybuffer', 

// Menggunakan tipe respons blob untuk file binary atau menggunakan array buffer tetap saja error

        method: 'get',
     
      })
        .then((response) => {
          this.forceFileDownload(response);
        })
        .catch(() => console.log('error occured'));
    },

**Comment by xuri** [comment] 2024-12-23 08:05
Thanks for your feedback, I don't think this problem was caused by this library. Here is [an example of working with HTTP server](https://xuri.me/excelize/en/workbook.html#OpenReader) in the documentation for your reference.

**Comment by danzf** [comment] 2024-12-23 08:27
<img width="405" alt="Jepretan Layar 2024-12-23 pukul 15 26 24" src="https://github.com/user-attachments/assets/a74f8d9a-3687-44c7-a6eb-3928e12388ad" />

saya menggungan echo untuk http ResponseWriter
tapi error

**Comment by xuri** [comment] 2024-12-23 10:28
Please reference [the example of Excelize working with HTTP server](https://xuri.me/excelize/en/workbook.html#OpenReader).

**Comment by danzf** [comment] 2024-12-23 13:29
Not working i try with open data stream

Pada Sen, 23 Des 2024 17.28, xuri ***@***.***> menulis:

**Comment by danzf** [comment] 2024-12-23 13:30
Doyou give me example probel with my code?

Pada Sen, 23 Des 2024 20.30, Danial Bachtiar ***@***.***> menulis:

**Comment by danzf** [comment] 2024-12-24 00:38
iam cant reference [the example of Excelize working with HTTP server](https://xuri.me/excelize/en/workbook.html#OpenReader).
insert to my code func (h *BookingMuseumHandler) DownloadExcels(c echo.Context) error {
data, _, err := h.bookingUcase.Fetch(ctx, au, &params)
if err != nil {
    return err
}

// Prepare the response data
pubRes := []domain.ListBookingMuseumDataResponse{}
for _, row := range data {
    res := domain.ListBookingMuseumDataResponse{
        ID:                row.ID,
        Nama:              row.PengunjungBookings.Nama,
        Email:             row.PengunjungBookings.Email,
        Kategori:          row.KategoriBookings.Nama,
        Sesi:              row.SesiBookings.Nama,
        JumlahPengunjung:  row.JumlahPengunjung,
        TanggalBerkunjung: row.TanggalBerkunjung,
        Dokumen:           row.DocBookings.Doc,
        BuktiBayarBookings: row.BuktiBayarBookings.Bukti,
        Status:            row.Status,
    }

    pubRes = append(pubRes, res)
}
// Create a new Excel file
f := excelize.NewFile()
index, err := f.NewSheet("Booking Museum")
if err != nil {
    return err
}
f.SetActiveSheet(index)
// Set header
headers := []string{
    "ID", "Nama", "Email", "Kategori", "Sesi", "Jumlah Pengunjung", "Tanggal Berkunjung", "Dokumen", "Bukti Bayar", "Status",
}
for col, header := range headers {
    f.SetCellValue("Booking Museum", fmt.Sprintf("%s1", string('A'+col)), header)
}
// Write data to Excel file
for i, res := range pubRes {
    f.SetCellValue("Booking Museum", fmt.Sprintf("A%d", i+2), strconv.FormatInt(res.ID, 10))
    f.SetCellValue("Booking Museum", fmt.Sprintf("B%d", i+2), res.Nama)
    f.SetCellValue("Booking Museum", fmt.Sprintf("C%d", i+2), res.Email)
    f.SetCellValue("Booking Museum", fmt.Sprintf("D%d", i+2), res.Kategori)
    f.SetCellValue("Booking Museum", fmt.Sprintf("E%d", i+2), res.Sesi)
    f.SetCellValue("Booking Museum", fmt.Sprintf("F%d", i+2), strconv.FormatInt(res.JumlahPengunjung, 10))
    f.SetCellValue("Booking Museum", fmt.Sprintf("G%d", i+2), res.TanggalBerkunjung)
    f.SetCellValue("Booking Museum", fmt.Sprintf("H%d", i+2), res.Dokumen)
    f.SetCellValue("Booking Museum", fmt.Sprintf("I%d", i+2), res.BuktiBayarBookings)
    f.SetCellValue("Booking Museum", fmt.Sprintf("J%d", i+2), res.Status)
}
if err := f.SaveAs("temp_booking_museum.xlsx"); err != nil {
	return err
}
buf := new(bytes.Buffer)
if err := f.Write(buf); err != nil {
	return c.JSON(500, "Failed to write Excel data to memory")
}
c.Response().Header().Set("Content-Disposition", "attachment; filename=booking_data.xlsx")
c.Response().Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
c.Response().Header().Set("Cache-Control", "no-store, no-cache, must-revalidate, proxy-revalidate")
c.Response().Header().Set("Pragma", "no-cache")
c.Response().Header().Set("Transfer-Encoding", "chunked")
// Kirimkan data dalam bentuk byte array (Blob)
return c.Blob(200, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", buf.Bytes())
}

**Comment by xuri** [comment] 2024-12-24 01:20
Here is an example for sending a xlsx File as a response to an HTTP Request using Gin based on your code, you can use the [`Write`](https://pkg.go.dev/github.com/xuri/excelize/v2#File.Write) function get saved workbook content without a touch file system, also reference the issue #744.

```diff
package main

import (
    "bytes"
    "fmt"
    "net/http"

    "github.com/gin-gonic/gin"
    "github.com/xuri/excelize/v2"
)

func ExportExcel(c *gin.Context) {
    // Data yang akan diekspor ke Excel
    data := []struct {
        ID    int    `json:"id"`
        Name  string `json:"name"`
        Age   int    `json:"age"`
        Email string `json:"email"`
    }{
        {ID: 1, Name: "John Doe", Age: 29, Email: "john.doe@example.com"},
        {ID: 2, Name: "Jane Smith", Age: 34, Email: "jane.smith@example.com"},
        {ID: 3, Name: "Bob Johnson", Age: 45, Email: "bob.johnson@example.com"},
    }

    // Membuat file Excel baru
    f := excelize.NewFile()

    // Menulis header
    f.SetCellValue("Sheet1", "A1", "ID")
    f.SetCellValue("Sheet1", "B1", "Name")
    f.SetCellValue("Sheet1", "C1", "Age")
    f.SetCellValue("Sheet1", "D1", "Email")

    // Menulis data ke Excel
    for i, d := range data {
        row := i + 2 // Dimulai dari baris ke-2
        f.SetCellValue("Sheet1", fmt.Sprintf("A%d", row), d.ID)
        f.SetCellValue("Sheet1", fmt.Sprintf("B%d", row), d.Name)
        f.SetCellValue("Sheet1", fmt.Sprintf("C%d", row), d.Age)
        f.SetCellValue("Sheet1", fmt.Sprintf("D%d", row), d.Email)
    }

    // Menyimpan file Excel
-   filePath := "./data.xlsx"
-   if err := f.SaveAs(filePath); err != nil {
-       c.JSON(http.StatusInternalServerError, gin.H{
-           "error": fmt.Sprintf("failed to save file: %v", err),
-       })
-       return
-   }
-
-   // Mengirim file sebagai response
-   c.Header("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
-   c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=%s", "data.xlsx"))
-   c.File(filePath)
-
-   // Menghapus file setelah dikirim (untuk menghindari tumpukan file sementara)
-   defer os.Remove(filePath)
+   filePath := "data.xlsx"
+
+   var b bytes.Buffer
+   if err := f.Write(&b); err != nil {
+       c.JSON(http.StatusInternalServerError, err.Error())
+       return
+   }
+   if err := f.Close(); err != nil {
+       c.JSON(http.StatusInternalServerError, err.Error())
+       return
+   }
+   c.Header("Content-Description", "File Transfer")
+   c.Header("Content-Disposition", "attachment; filename="+filePath)
+   c.Data(http.StatusOK, "application/octet-stream", b.Bytes())
}

func main() {
    // Membuat router Gin
    r := gin.Default()

    // Menyusun route untuk export Excel
    r.GET("/export-excel", ExportExcel)

    // Menjalankan server
    r.Run(":8080")
}
```

**Comment by danzf** [comment] 2024-12-24 02:13
me use package "github.com/labstack/echo/v4"
c.Data not working

**Comment by danzf** [comment] 2024-12-24 02:20
me run your example 
result postman 
<img width="839" alt="Jepretan Layar 2024-12-24 pukul 09 20 42" src="https://github.com/user-attachments/assets/f00f1d3a-ad19-4e66-8cc3-dd55e4e1c209" />

**Comment by xuri** [comment] 2024-12-24 02:32
Please visit "http://127.0.0.1:8080/export-excel" in your web browser or another client. I don't think this is caused by this library. I saw you're using Gin web framework in your comments.

**Comment by danzf** [comment] 2024-12-24 03:09
<img width="1298" alt="Jepretan Layar 2024-12-24 pukul 10 02 12" src="https://github.com/user-attachments/assets/30f073d1-aa6e-42ad-916c-8498ec398c41" />
response for browser

**Comment by xuri** [comment] 2024-12-24 03:13
The workbook will be download when you open the URL.

**Comment by xuri** [comment] 2024-12-24 03:14
Please run the code I replied to above. The workbook will be downloaded when you open the URL.

**Comment by danzf** [comment] 2024-12-24 03:19
func NewBookingMuseumHandler(p *echo.Group, r *echo.Group, sp domain.BookingMuseumUsecase, logger *utils.Logrus) {
	handler := &BookingMuseumHandler{
		bookingMuseumUcase: sp,
		// apm:      apm,
		Logger: logger,
	}
	r.POST("/booking-museums", handler.Store)
	r.GET("/booking-museums", handler.Fetch)
	r.GET("/booking-museums/excel", handler.ExportExcel)
}


func (h *BookingMuseumHandler) ExportExcel(c echo.Context) (err error) {
    // Data yang akan diekspor ke Excel
    data := []struct {
        ID    int    `json:"id"`
        Name  string `json:"name"`
        Age   int    `json:"age"`
        Email string `json:"email"`
    }{
        {ID: 1, Name: "John Doe", Age: 29, Email: "john.doe@example.com"},
        {ID: 2, Name: "Jane Smith", Age: 34, Email: "jane.smith@example.com"},
        {ID: 3, Name: "Bob Johnson", Age: 45, Email: "bob.johnson@example.com"},
    }

    // Membuat file Excel baru
    f := excelize.NewFile()

    // Menulis header
    f.SetCellValue("Sheet1", "A1", "ID")
    f.SetCellValue("Sheet1", "B1", "Name")
    f.SetCellValue("Sheet1", "C1", "Age")
    f.SetCellValue("Sheet1", "D1", "Email")

    // Menulis data ke Excel
    for i, d := range data {
        row := i + 2 // Dimulai dari baris ke-2
        f.SetCellValue("Sheet1", fmt.Sprintf("A%d", row), d.ID)
        f.SetCellValue("Sheet1", fmt.Sprintf("B%d", row), d.Name)
        f.SetCellValue("Sheet1", fmt.Sprintf("C%d", row), d.Age)
        f.SetCellValue("Sheet1", fmt.Sprintf("D%d", row), d.Email)
    }

 filePath := "data.xlsx"

 var b bytes.Buffer
 if err := f.Write(&b); err != nil {
     c.JSON(http.StatusInternalServerError, err.Error())
     return err
 }
 if err := f.Close(); err != nil {
     c.JSON(http.StatusInternalServerError, err.Error())
     return err
 }
 c.Response().Header().Set("Content-Description", "File Transfer")
 c.Response().Header().Set("Content-Disposition", "attachment; filename="+filePath)
 c.Blob(http.StatusOK, "application/octet-stream", b.Bytes())
 return nil
}

hasil api export excel diatas sudah saya panggil dan hasilnya seperti response biner diatas

**Comment by xuri** [comment] 2024-12-24 03:23
Could you show us a complete, standalone example program or reproducible demo with main function? You provided code can't build directly.
