### ISSUE TITLE
Set cell value with over maximum characters limit 超长文本写入单元格

### ISSUE THREAD

**Issue by wangdzhao** [qax-os/excelize#1530] opened 2023-04-23 02:54 UTC
作者你好，使用流往单元格写入文章数据，一些文章数据超过了TotalCellChars，代码会执行完毕，但是生成的excel打不开，使用其他方式写入，发现底层会对长度进行截取，请问对于超长文本写入单元格，有没有提供解决方案呢

**Comment by xuri** [comment] 2023-04-23 05:18
I have test with the master branch code, and it works well. Could you follow the issue template, provide a reproducible demo with simplified codes?

**Comment by xuri** [comment] 2023-04-23 05:18
Thanks for your issue. I have test with the master branch code, and it works well. Could you follow the issue template, provide a reproducible demo with simplified codes?

**Comment by wangdzhao** [comment] 2023-04-23 05:18
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xuri** [comment] 2023-04-23 05:50
According to the community feedback, this issue was duplicated with issues #1518 and #1519, because these issues have been fixed, so I'll close this issue.

**Closed by xuri** 2023-04-23 05:50 UTC
Labels: needs more info

**Comment by yxs1987** [comment] 2023-07-07 03:31
yes,i use version v2 have the same problem.
the best resolution upgrade your version!

**Comment by wangdzhao** [comment] 2023-07-07 03:31
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
