### ISSUE TITLE
Unresolved reference for `Close()`

### ISSUE THREAD

**Issue by tg-mvooges** [qax-os/excelize#1094] opened 2021-12-14 12:23 UTC
I have copied the example from [qax-os/excelize#reading-spreadsheet](https://github.com/qax-os/excelize#reading-spreadsheet) to my code and I'm getting the following error ([Screenshot](https://ibb.co/NT4TfB6)):

```
defer func() {
    //// Close the spreadsheet.
    if err := f.Close(); err != nil {  // <----- this Close gets the error "Unresolved reference"
        fmt.Println(err)
    }
}()
```
I can comment the line and the code still opens the Excel file as expected, but I assume that the close is there for a reason.

**Steps to reproduce the issue:**
1. Copy [the snippet from the docs](https://github.com/qax-os/excelize#reading-spreadsheet) 
2. Try to run it.

**Describe the results you received:**
./main.go:38:14: f.Close undefined (type *excelize.File has no field or method Close)

**Describe the results you expected:**
Not that error and normal usage

**Output of `go version`:**
go1.17.1 darwin/amd64

**Excelize version or commit ID:**
github.com/xuri/excelize/v2 v2.4.1

**Comment by xuri** [comment] 2021-12-14 14:55
This issue duplicate with #1025, #1042 and #1091, the `Close` method will be released in the next version: [v2.5.0](https://xuri.me/excelize/en/releases/v2.5.0.html).

**Comment by emicklei** [comment] 2021-12-15 12:58
can't we have a 2.4.2 fix release?

**Comment by tg-mvooges** [comment] 2021-12-15 14:00
> This issue duplicate with #1025, #1042 and #1091, the `Close` method will be released in the next version: [v2.5.0](https://xuri.me/excelize/en/releases/v2.5.0.html).

Thanks for your reply. Do you have a timeline when that will be release? Because at this moment my code wont run. I can keep it off for testing, but not for running 24/7.

**Comment by xuri** [comment] 2021-12-16 02:09
Hi @emicklei, the `Close` API will be release in the next version 2.5.0, it close underlying temp file and reset the in-memory buffer for opening large scale spreadsheet, if you are using 2.4.1 and early version, there no temp files generated, so that not a bug.

**Comment by xuri** [comment] 2021-12-16 02:12
Hi @tg-mvooges, ss the [document](https://xuri.me/excelize/en/releases/v2.5.0.html) and [project](../projects) list says: the next version 2.5.0 will be released on January 3rd, 2022.

**Closed** 2021-12-23 06:27 UTC
Labels: duplicate
