### ISSUE TITLE
time parse error

### ISSUE THREAD

**Issue by hotfireeagle** [qax-os/excelize#1093] opened 2021-12-10 17:04 UTC
the excel data:

![image](https://user-images.githubusercontent.com/13727777/145612908-e9703e5b-0099-4929-9fc5-235234727920.png)

after parse, the output is:

![image](https://user-images.githubusercontent.com/13727777/145612969-bec34a37-4081-4a11-ac07-d31d4b65ec30.png)

the code is:

![image](https://user-images.githubusercontent.com/13727777/145613094-b674eb0c-778f-4893-995d-dc4ed8686b54.png)

**Comment by danielbprice** [comment] 2021-12-10 18:15
(I am not a maintainer here, but): did you try running from the top of the tree, i.e. from master?  Because other time parsing bugs have been fixed since the most recent release.  I recently hit https://github.com/qax-os/excelize/issues/1080 which isn't that different.

**Comment by hotfireeagle** [comment] 2021-12-11 06:42
my excelize version is v2.4.2

**Comment by xuri** [comment] 2021-12-11 08:25
This issue is duplicated with #764, #1030, #1070 and #1073 please upgrade to the master branch code, and this patch will be released in the next version [v2.5.0](https://xuri.me/excelize/en/releases/v2.5.0.html):

```go
go get -u github.com/xuri/excelize/v2@master
go mod tidy
```

**Closed** 2021-12-11 08:45 UTC
Labels: duplicate

**Comment by skytodmoon** [comment] 2021-12-20 06:14
@xuri @danielbprice Have you resolved this problem? I met same after: 
go get -u github.com/xuri/excelize/v2@master
go mod tidy
version:v2.4.2-0.20211219053624-6051434bf898

**Comment by xuri** [comment] 2021-12-20 06:24
This issue has been fixed. Could you provide spreadsheet attachment and standalone code to reproduce this issue?

**Comment by skytodmoon** [comment] 2021-12-20 06:31
[Uploading test.xlsx…]()

```
func main() {
	f, err := excelize.OpenFile("test.xlsx")
	if err != nil {
		fmt.Println(err)
		return
	}
	defer func() {
		// Close the spreadsheet.
		if err := f.Close(); err != nil {
			fmt.Println(err)
		}
	}()
	// Get value from cell by given worksheet name and axis.
	cell, err := f.GetCellValue("Sheet1", "B2")
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(cell)
	// Get all the rows in the Sheet1.
	rows, err := f.GetRows("Sheet1")
	if err != nil {
		fmt.Println(err)
		return
	}
	for _, row := range rows {
		for _, colCell := range row {
			//fmt.Print(colCell, "\t")
			fmt.Printf("%s\n",colCell)
		}
		fmt.Println()
	}
}
```

result:

'12-17-21

12-18-21

12-19-21

12-20-21

12-21-21

12-22-21
'

**Comment by xuri** [comment] 2021-12-20 07:40
The file attachments upload failed.

**Comment by skytodmoon** [comment] 2021-12-20 08:03
@xuri uploaded.

**Comment by xuri** [comment] 2021-12-20 11:28
This patch fixed the accuracy issue on parsing cells with time number format in some cases, but not related to language location. The library support parsing build-in date and time number format under English (United States) currently, so the cell value should be concat with a dash (not slash) after applying the number format, I'll consider adding language location support later.
