### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by hvritual** [qax-os/excelize#1155] opened 2022-02-19 15:05 UTC
**Description**
最新2.5版本遇到内存泄漏

**Steps to reproduce the issue:**
`
for {
		f, err := excelize.OpenFile("index.xlsx")
		if err != nil {
			fmt.Println(err)
			return
		}
		rows, err := f.GetRows("Sheet1")
		if err != nil {
			fmt.Println(err)
		} else {
			for _, row := range rows {
				for _, colCell := range row {
					fmt.Print(colCell, "\t")
				}
				fmt.Println()
			}
		}

		if err := f.Close(); err != nil {
			fmt.Println(err)
		}

		time.Sleep(time.Second)
	}
`

**Describe the results you received:**

**Describe the results you expected:**
上述代码回出现内存持续增长

**Output of `go version`:**

```text
go version go1.17.6 darwin/amd64
```

**Excelize version or commit ID:**

```text
github.com/xuri/excelize/v2 v2.5.0
```

**Environment details (OS, Microsoft Excel™ version, physical, etc.):**

**Comment by xuri** [comment] 2022-02-20 05:28
Thanks for your feedback, but I can't reproduce this issue with a 10-minute run, the memory will be free after GC interval. Could you provide more details and spreadsheet attachments without confidential info?

**Comment by hvritual** [comment] 2022-02-20 06:41
maybe it's relate to `encoding/xml.(*Decoder).rawToken`, that call  always in memory of heap, not recycle.

**Comment by xuri** [comment] 2022-02-24 14:50
Could you provide more details about this issue?

**Comment by xuri** [comment] 2022-04-26 03:20
It seems still not have enough info of code and attachments to reproduce this issue, so I'll close this issue, if you have any questions, please let me know to reopen this anytime.

**Closed by xuri** 2022-04-26 03:20 UTC
Labels: needs more info
